import { ProfessionalCourse } from "./firebaseData";

// Demo data for professional courses with correct IDs matching CursosProfesionales page
export const getDemoProfessionalCourses = (): ProfessionalCourse[] => {
  return [
    {
      id: "programador-desde-cero",
      name: "Programador desde cero",
      description:
        "Aprende programación desde los fundamentos hasta crear aplicaciones completas",
      image: "💻",
      category: "Tecnología",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 200 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios pr��cticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "6-8 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "auxiliar-veterinaria",
      name: "Auxiliar de Veterinaria",
      description: "Cuidado y asistencia profesional en clínicas veterinarias",
      image: "🐕",
      category: "Sanidad Animal",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 180 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "peluqueria-profesional",
      name: "Peluquería Profesional",
      description: "Técnicas de corte, peinado y estilismo profesional",
      image: "✂️",
      category: "Belleza",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 80 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "3-4 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "electricista",
      name: "Electricista",
      description: "Instalaciones eléctricas residenciales e industriales",
      image: "⚡",
      category: "Oficios",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 250 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "fontaneria",
      name: "Fontanería",
      description: "Instalaciones de agua, calefacción y saneamiento",
      image: "🔧",
      category: "Oficios",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 220 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "estetica-belleza",
      name: "Estética y Belleza",
      description:
        "Tratamientos faciales, corporales y técnicas de embellecimiento",
      image: "✨",
      category: "Belleza",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 90 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "3-5 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "diseno-grafico",
      name: "Diseño Gráfico",
      description:
        "Creación de diseños visuales, logos y material publicitario",
      image: "🎨",
      category: "Creatividad",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 190 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "community-manager",
      name: "Community Manager",
      description:
        "Gestión de redes sociales y estrategias de comunicación digital",
      image: "📱",
      category: "Marketing",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 75 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "2-3 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "edicion-video",
      name: "Edición de Vídeo",
      description: "Postproducción audiovisual profesional",
      image: "🎬",
      category: "Creatividad",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 210 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "3-5 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "marketing-digital",
      name: "Marketing Digital",
      description: "Estrategias de marketing online y publicidad digital",
      image: "📈",
      category: "Marketing",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 180 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "asistente-administrativo",
      name: "Asistente Administrativo",
      description: "Gestión de oficina y apoyo administrativo",
      image: "📋",
      category: "Administración",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 70 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "2-4 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "contabilidad-facturacion",
      name: "Contabilidad y Facturación",
      description: "Gestión contable y fiscal para empresas",
      image: "🧮",
      category: "Administración",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 200 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "5-7 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "ingles-profesionales",
      name: "Inglés para Profesionales",
      description: "Inglés empresarial y comunicación internacional",
      image: "🌍",
      category: "Idiomas",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 160 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "6-12 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "auxiliar-enfermeria",
      name: "Auxiliar de Enfermería",
      description: "Cuidados básicos de salud y asistencia sanitaria",
      image: "💊",
      category: "Sanidad",
      difficulty: "hard",
      pricing: { monthly_subscription: 20, one_time_payment: 450 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "8-12 meses",
      totalModules: 20,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "cuidados-personas-mayores",
      name: "Cuidados para Personas Mayores",
      description: "Atención geriátrica especializada y cuidados domiciliarios",
      image: "👴",
      category: "Sanidad",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 170 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "4-6 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "cocina-profesional",
      name: "Cocina Profesional",
      description: "Técnicas culinarias y gestión de cocina",
      image: "👨‍🍳",
      category: "Gastronomía",
      difficulty: "medium",
      pricing: { monthly_subscription: 20, one_time_payment: 190 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "6-8 meses",
      totalModules: 12,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "atencion-cliente",
      name: "Atención al Cliente",
      description: "Servicio al cliente excepcional y resolución de conflictos",
      image: "📞",
      category: "Comercial",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 65 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "2-3 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "ciberseguridad-basica",
      name: "Ciberseguridad Básica",
      description: "Protección de sistemas y seguridad informática",
      image: "🛡️",
      category: "Tecnología",
      difficulty: "hard",
      pricing: { monthly_subscription: 20, one_time_payment: 400 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "6-10 meses",
      totalModules: 20,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "programacion-web-fullstack",
      name: "Programación Web Full Stack",
      description: "Desarrollo completo de aplicaciones web modernas",
      image: "🌐",
      category: "Tecnología",
      difficulty: "hard",
      pricing: { monthly_subscription: 20, one_time_payment: 500 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "8-12 meses",
      totalModules: 20,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "gestion-redes-sociales",
      name: "Gestión de Redes Sociales",
      description:
        "Estrategias de contenido y crecimiento en plataformas sociales",
      image: "📊",
      category: "Marketing",
      difficulty: "easy",
      pricing: { monthly_subscription: 20, one_time_payment: 85 },
      features: [
        "Acceso completo al contenido",
        "Chat con IA especializada",
        "Ejercicios prácticos",
        "Certificado de finalización",
        "Acceso de por vida (pago único)",
      ],
      isPublic: true,
      estimatedDuration: "2-4 meses",
      totalModules: 8,
      certificateAvailable: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];
};
